# Generated by Django 5.2.16 on 2026-07-28 21:23

import apps.messaging.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(db_column='message_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, db_column='content')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='SENT', max_length=12)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('client_nonce', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='spaces.chatspace')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='spaces.topic')),
            ],
            options={
                'ordering': ('sent_at', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=apps.messaging.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=127)),
                ('size', models.PositiveBigIntegerField()),
                ('category', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['space', 'status', 'sent_at'], name='messaging_m_space_i_4d0eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['topic', 'status', 'sent_at'], name='messaging_m_topic_i_3050ad_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['status', 'scheduled_for'], name='messaging_m_status_eb22a5_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'status', 'scheduled_for'], name='messaging_m_sender__c17124_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_nonce__isnull', False)), fields=('sender', 'client_nonce'), name='messaging_sender_client_nonce_unique'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scheduled_for__isnull', False), ('status', 'PENDING')), models.Q(('status', 'PENDING'), _negated=True), _connector='OR'), name='messaging_pending_requires_schedule'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', False), ('status', 'SENT')), models.Q(('status', 'SENT'), _negated=True), _connector='OR'), name='messaging_sent_requires_timestamp'),
        ),
    ]
