# Generated by Django 5.2.16 on 2026-07-28 21:23

import apps.spaces.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSpace',
            fields=[
                ('id', models.UUIDField(db_column='space_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type', models.CharField(choices=[('DIRECT', 'Direct'), ('GROUP', 'Group'), ('CHANNEL', 'Channel')], max_length=10)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.spaces.models.space_avatar_upload_path)),
                ('direct_key', models.CharField(blank=True, editable=False, max_length=73, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(db_column='role_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('can_send_messages', models.BooleanField(default=True)),
                ('can_send_media', models.BooleanField(default=True)),
                ('can_manage_topics', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('can_delete_messages', models.BooleanField(default=False)),
                ('can_manage_roles', models.BooleanField(default=False)),
                ('can_manage_space', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='spaces.chatspace')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='spaces.role')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='spaces.chatspace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('joined_at',),
            },
        ),
        migrations.AddField(
            model_name='chatspace',
            name='members',
            field=models.ManyToManyField(related_name='chat_spaces', through='spaces.SpaceMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(db_column='topic_id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='spaces.chatspace')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='spaces_role_name_unique_per_space'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('space',), name='spaces_one_default_role_per_space'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['space', 'user'], name='spaces_spac_space_i_98f330_idx'),
        ),
        migrations.AddIndex(
            model_name='spacemembership',
            index=models.Index(fields=['user', 'space'], name='spaces_spac_user_id_364044_idx'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.UniqueConstraint(fields=('user', 'space'), name='spaces_membership_user_space_unique'),
        ),
        migrations.AddIndex(
            model_name='chatspace',
            index=models.Index(fields=['type', 'updated_at'], name='spaces_chat_type_198779_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatspace',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direct_key__isnull', False), ('type', 'DIRECT')), models.Q(('direct_key__isnull', True), ('type__in', ('GROUP', 'CHANNEL'))), _connector='OR'), name='spaces_direct_key_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='spaces_topic_name_unique_per_channel'),
        ),
    ]
